channels:
  - conda-forge
  - defaults
dependencies:
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.5
  - conda=4.14.0
  - conda-package-handling=1.8.1
  - cryptography=37.0.4
  - icu=68.1
  - idna=3.3
  - krb5=1.19.3
  - libarchive=3.5.2
  - libcurl=7.83.1
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libiconv=1.16
  - libmamba=0.25.0
  - libmambapy=0.25.0
  - libnghttp2=1.47.0
  - libsolv=0.7.22
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libuv=1.39.0
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.25.0
  - ncurses=6.3
  - nodejs=16.13.1
  - openssl=1.1.1q
  - pip=22.2.2
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.10.6
  - python_abi=3.10
  - readline=8.1.2
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.28.1
  - ruamel_yaml=0.15.80
  - setuptools=65.3.0
  - six=1.16.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.0
  - tzdata=2022c
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zlib=1.2.12
  - zstd=1.5.2
